---
driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/integration/tk_encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  environments_path: test/environments
  environment: kitchen

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[telegraf::default]
      - recipe[sparrow]
    attributes:
     sparrow:
       plugin:
         list: [
           'outth-telegraf'
         ]

